package com.bank.entity;

import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

// MongoDB document mapped to the 'accounts' collection
@Document(collection = "accounts")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Account {

    // MongoDB ObjectId stored as a hex string — replaces Long auto-increment
    @Id
    private String id;

    // Unique 10-digit account number generated by the system on creation
    @Indexed(unique = true)
    private String accountNumber;

    @NotBlank(message = "Holder name is required")
    private String holderName;

    @Email(message = "Must be a valid email address")
    @NotBlank(message = "Email is required")
    private String email;

    // 10-digit Indian mobile number
    private String phone;

    // Date of birth for KYC — must be 18+
    private LocalDate dateOfBirth;

    // Full residential address for KYC
    private String address;

    // Type of government ID: AADHAR, PAN, PASSPORT
    private String idType;

    // Government ID number (stored as-is for simulation)
    private String idNumber;

    // BCrypt-hashed password — plain text is shown ONCE after account creation
    private String password;

    // Balance must never be negative for any account
    @DecimalMin(value = "0.0", message = "Balance cannot be negative")
    private BigDecimal balance;

    // Auto-set by @EnableMongoAuditing when the document is first inserted
    @CreatedDate
    private LocalDateTime createdAt;

    // Tracks if the account is usable or has been closed
    @Builder.Default
    private AccountStatus status = AccountStatus.ACTIVE;

    // Transient — not persisted to MongoDB, only returned to client once on creation
    @org.springframework.data.annotation.Transient
    private String plainTextPassword;
}
